[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/ds-test/src, @openzeppelin/=lib/openzeppelin-contracts, @balancer-labs/=lib/balancer-v2-monorepo, "]

[fmt]
line_length = 100
number_underscore = "thousands"

[rpc_endpoints]
eth = "https://eth.llamarpc.com"
arb = "https://arbitrum.llamarpc.com"
